org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

mod_id=more_functionalstorage_upgrade
mod_name=More Functional Storage upgrade
mod_license=MIT
mod_version=1.0.0-mc26.1.2-neoforge
mod_group_id=com.chinaex123.more_functionalstorage_upgrade
