modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/WitherRedstone/More-Functional-Storage-Upgrade"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/more-functional-storage-upgrade"
logoFile="logo.png"
authors="ChinaEX123"
description='''
Add more upgrades to Functional Storage.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="titanium"
    type="required"
    versionRange="[4.0.40,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="functionalstorage"
    type="required"
    versionRange="[1.5.5,)"
    ordering="AFTER"
    side="BOTH"
